services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    logging:
      driver: "none"

    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "True"
    volumes:
      - dbbackup:/dbbackup

volumes:
  dbbackup:
    driver: local
